config/routes.rb
class Spree::PossiblePage
  def self.matches?(request) 
    return false if request.path =~ /(^\/+(admin|account|cart|checkout|content|login|pg\/|orders|products|s\/|session|signup|shipments|states|t\/|tax_categories|user)+)/
    !Spree::Page.active.find_by_path(request.path).nil?
  end
end

Spree::Core::Engine.routes.append do
  
  namespace :admin do
    
    resources :pages, :constraints => { :id => /.*/ } do
      collection do
        post :update_positions
      end
    
      resources :contents do
        collection do
          post :update_positions
        end
      end
    
      resources :images, :controller => "page_images" do
        collection do
          post :update_positions
        end
      end
    end

  end
  
  constraints(Spree::PossiblePage) do
    get '*page_path', :to => 'pages#show', :as => :page
  end
  
end

app/views/spree/admin/pages/_form.html.erb
<%= form.field_container :title do %>
  <%= form.label :title, t('page.title') %> <span class="required">*</span><br />
  <%= form.text_field :title, :class => "title"  %>
  <%= error_message_on :page, :title %>
<% end %>

<%= form.field_container :meta_title do %>
  <%= form.label :meta_title, t('page.meta_title') %><br />
  <%= form.text_field :meta_title, :class => "text"  %>
  <%= error_message_on :page, :meta_title %>
<% end %>

<%= form.field_container :meta_description do %>
  <%= form.label :meta_description, t('page.meta_description') %><br />
  <%= form.text_field :meta_description, :class => "text"  %>
  <%= error_message_on :page, :meta_description %>
<% end %>

<%= form.field_container :meta_keywords do %>
  <%= form.label :meta_keywords, t('page.meta_keywords') %><br />
  <%= form.text_field :meta_keywords, :class => "text"  %>
  <%= error_message_on :page, :meta_keywords %>
<% end %>

<%= form.field_container :accessible do %>
  <%= form.check_box :accessible, :class => "text"  %> &nbsp;
  <%= form.label :accessible, t('page.accessible') %>
  <em><%= t('page.explain_accessible') %></em>
  <%= error_message_on :page, :accessible %>
<% end %>

<div id="field_path">

  <%= form.field_container :path do %>
    <%= form.label :path, t('page.path') %><br />
    <%= form.text_field :path, :class => "text"  %>
    <%= error_message_on :page, :path %>
  <% end %>

  <%= form.field_container :visible do %>
    <%= form.check_box :visible, :class => "text" %> &nbsp;
    <%= form.label :visible, t('page.visible') %> 
    &ndash; <em><%= t('page.explain_visible') %></em>
    <%= error_message_on :page, :visible %>
  <% end %>
  
  <div id="field_nav_title">
    <%= form.field_container :nav_title do %>
      <%= form.label :nav_title, t('page.nav_title') %><br />
      <%= form.text_field :nav_title, :class => "text"  %>
      <%= error_message_on :page, :nav_title %>
    <% end %>
  </div>

</div>

<script type="text/javascript">
//<![CDATA[

  $(document).ready(function() {
  
  	$('#page_accessible').change(function(evt) {
      $('#field_path').toggle(this.checked);
    }).change();
    
  	$('#page_visible').change(function(evt) {
      $('#field_nav_title').toggle(this.checked);
    }).change();

  });     
  
//]]>
</script>

app/views/spree/admin/pages/edit.html.erb
<%= render :partial => 'spree/admin/shared/page_tabs', :locals => {:current => 'Page Details'} %>

<% if @page.try(:errors).present? %>
  <%= render 'spree/shared/error_messages', :target => @page %>
<% end %>

<%= form_for([:admin, @page]) do |f| %>
  <%= render "form", :form => f %>
  <p class="form-buttons">
    <%= button t("update") %> <%= t('or') %> <%= link_to t('cancel'), collection_url %>
  </p>
<% end %>

app/views/spree/admin/pages/index.html.erb
<div class='toolbar'>
  <ul class='actions'>
    <li>
      <p><%= button_link_to t('.new_page'), new_object_url, :icon => 'add' %></p>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%= t('.listing_pages') %></h1>

<table class="index sortable" data-sortable-link="<%= update_positions_admin_pages_url -%>">
  <thead>
  <tr>
      <th><%= sort_link @search, :title, t("page.title") %></th>
      <th><%= sort_link @search, :path, t("page.path") %></th>
      <th><%= sort_link @search, :accessible, t("page.accessible") %></th>
      <th><%= sort_link @search, :visible, t("page.visible") %></th>
      <th><%= t("action") %></th>
  </tr>
  </thead>
  <tbody>
    <%- @collection.each do |page|%>
    <tr id="<%= spree_dom_id page %>">
      <td><span class="handle">&nbsp;</span>&nbsp; <%=link_to page.title, object_url(page) %></td>
      <td><%= page.path %></td>
      <td><%= page.accessible %></td>
      <td><%= page.visible %></td>
      <td>
        <%= link_to_with_icon :accept, t('preview'), page.path, :onclick => 'window.open(this.href);return false;' %> &nbsp;
        <%= link_to_with_icon :pages, t('page.contents'), admin_page_contents_path(page) %> &nbsp;
        <%= link_to_edit page %> &nbsp;
        <%= link_to_delete page %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @collection %>

<% content_for :sidebar do %>
  <div class="box">
    <h3><%= t(:search) %></h3>
    <%= search_form_for [:admin, @search] do |f| %>
      <p>
        <%= f.label :title_cont, t('page.title') %><br />
        <%= f.text_field :title_cont, :size => 25 %>
      </p>
      <p>
        <%= f.label :path_cont, t('page.path') %><br />
        <%= f.text_field :path_cont, :size => 25 %>
      </p>
      <p><%= button t("search") %></p>
    <% end %>
  </div>
<% end %>

app/views/spree/admin/pages/new.html.erb
<%#= render :partial => 'spree/admin/shared/contents_sub_menu' %>

<% if @page.try(:errors).present? %>
  <%= render 'spree/shared/error_messages', :target => @page %>
<% end %>

<h1><%= t('.new_page') %></h1>

<%= form_for([:admin, @page], :html => { :multipart => true }) do |f| %>
  <%= render "form", :form => f %>

  <p class="form-buttons">
    <%= button t('create') %> <%= t('or') %> <%= link_to t('cancel'), collection_url %>
  </p>
<% end %>

app/views/spree/admin/pages/show.html.erb
<%= render :partial => 'spree/admin/shared/page_tabs', :locals => {:current => "Page Details"} %>

<h3>Meta Data:</h3>
<p>
  <b><%= t('page.meta_title') %>:</b> <%= @page.meta_title %><br/>
  <b><%= t('page.meta_description') %>:</b> <%= @page.meta_description %><br/>
  <b><%= t('page.meta_keywords') %>:</b> <%= @page.meta_keywords %>
</p>

<hr/>

<% @page.contents.each do |content| %>
  
  <%= content.title %>
  
<% end %>

<p>
  <%= link_to_edit @page %> &nbsp;
  <%= link_to t('back'), collection_url %>
</p>