config/routes.rb
class Spree::PossiblePage
  def self.matches?(request) 
    return false if request.path =~ /(^\/+(admin|account|cart|checkout|content|login|pg\/|orders|products|s\/|session|signup|shipments|states|t\/|tax_categories|user)+)/
    !Spree::Page.active.find_by_path(request.path).nil?
  end
end

Spree::Core::Engine.routes.append do
  
  namespace :admin do
    
    resources :pages, :constraints => { :id => /.*/ } do
      collection do
        post :update_positions
      end
    
      resources :contents do
        collection do
          post :update_positions
        end
      end
    
      resources :images, :controller => "page_images" do
        collection do
          post :update_positions
        end
      end
    end

  end
  
  constraints(Spree::PossiblePage) do
    get '*page_path', :to => 'pages#show', :as => :page
  end
  
end

app/views/spree/admin/shared/_page_tabs.html.erb
<h1><%= (t('.editing_page') + " &ldquo;#{@page.title}&rdquo;").html_safe %></h1>

<% content_for :sidebar do %>

  <h3 class="name"><%= @page.title %></h3>
  <br clear="clear" />

  <ul class="sidebar post-menu">
    <li<%== ' class="active"' if current == t('.page_details') %>>
      <%= link_to t('.page_details'), edit_admin_page_url(@page) %>
    </li>      
    <li<%== ' class="active"' if current == "Contents" %>>
      <%= link_to t('.contents'), admin_page_contents_url(@page) %>
    </li>    
    <li<%== ' class="active"' if current == "Images" %>>
      <%= link_to t('.images'), admin_page_images_url(@page) %>
    </li>    
  </ul>
  <br clear="clear" />

<% end %>