config/routes.rb
class Spree::PossiblePage
  def self.matches?(request) 
    return false if request.path =~ /(^\/+(admin|account|cart|checkout|content|login|pg\/|orders|products|s\/|session|signup|shipments|states|t\/|tax_categories|user)+)/
    !Spree::Page.active.find_by_path(request.path).nil?
  end
end

Spree::Core::Engine.routes.append do
  
  namespace :admin do
    
    resources :pages, :constraints => { :id => /.*/ } do
      collection do
        post :update_positions
      end
    
      resources :contents do
        collection do
          post :update_positions
        end
      end
    
      resources :images, :controller => "page_images" do
        collection do
          post :update_positions
        end
      end
    end

  end
  
  constraints(Spree::PossiblePage) do
    get '*page_path', :to => 'pages#show', :as => :page
  end
  
end

app/models/spree/page_image.rb
class Spree::PageImage < Spree::Asset

  attr_accessible :viewable, :attachment, :alt

  validates_attachment_presence :attachment
  
  has_attached_file :attachment,
    :styles => Proc.new{ |clip| clip.instance.attachment_sizes },
    :default_style => :medium,
    :url => '/spree/pages/:id/:style/:basename.:extension',
    :path => ':rails_root/public/spree/pages/:id/:style/:basename.:extension'

  def image_content?
    attachment_content_type.to_s.match(/\/(jpeg|png|gif|tiff|x-photoshop)/)
  end

  def attachment_sizes
    sizes = {}
    if image_content?
      sizes.merge!(:mini => '48x48>', :small => '150x150>', :medium => '420x300>', :large => '900x650>')
      sizes.merge!(:slide => '950x250#') if viewable.respond_to?(:root?) && viewable.root?
    end
    sizes
  end

end

app/controllers/spree/admin/page_images_controller.rb
class Spree::Admin::PageImagesController < Spree::Admin::ResourceController
  
  before_filter :load_data

  create.before :set_viewable
  update.before :set_viewable
  destroy.before :destroy_before

  def update_positions
    params[:positions].each do |id, index|
      Spree::PageImage.update_all(['position=?', index], ['id=?', id])
    end
    respond_to do |format|
      format.js  { render :text => 'Ok' }
    end
  end
  
  private
  
  def location_after_save
    admin_page_images_url(@page)
  end

  def load_data
    @page = Spree::Page.find_by_path(params[:page_id])
  end

  def set_viewable
    @page_image.viewable = @page
  end

  def destroy_before
    @viewable = @page_image.viewable
  end

end

app/views/spree/admin/page_images/_form.html.erb
<p>
  <%= form.label :attachment %>:<br/>
  <%= form.file_field :attachment %>
</p>
<p>
  <%= form.label :alt %>:<br/>
  <%= form.text_field :alt, :class => 'text' %>
</p>

app/views/spree/admin/page_images/edit.html.erb
<%= render :partial => 'spree/admin/shared/page_tabs', :locals => {:current => "Images"} %>

<% if @page_image.try(:errors).present? %>
  <%= render 'spree/shared/error_messages', :target => @page_image %>
<% end %>

<%= form_for([:admin, @page.id, @page_image], :url => admin_page_image_url(@page, @page_image), :html => { :multipart => true }) do |f| %>
    <p>
      <%= label_tag ("thumbnail") %>:<br/>
      <%= link_to(image_tag(@page_image.attachment.url(:mini)), @page_image.attachment.url(:product)) %>
    </p>
    <%= render "form", :form => f %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    or <%= link_to t("cancel"), admin_page_images_url(@page), :id => "cancel_link" %>
  </p>
<% end %>

app/views/spree/admin/page_images/index.html.erb
<%= render :partial => 'spree/admin/shared/page_tabs', :locals => {:current => "Images"} %>

<table class="index sortable" data-sortable-link="<%= update_positions_admin_page_images_url(@page) -%>">
  <thead>
    <tr>
      <th><%= t("thumbnail") %></th>
      <th><%= t("alt_text") %></th>
      <th><%= t("action") %></th>
    </tr>
  </thead>
  <tbody>
    <% @page.images.each do |image| %>
      <tr id="<%= spree_dom_id(image) %>">
        <td><span class="handle">&nbsp;</span>&nbsp; <%= link_to(image_tag(image.attachment.url(:mini)), image.attachment.url(:large)) %></td>
        <td><%= image.alt %></td>
        <td class="actions">
          <%= link_to_with_icon('edit', t("edit"), edit_admin_page_image_url(@page, image)) %>
          &nbsp;
          <%= link_to_delete image, {:url => admin_page_image_url(@page, image) }%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div id="images"></div>
<br/>
<p>
    <%= link_to icon('add') + ' ' + t("new_image"), new_admin_page_image_url(@page), :id => "new_image_link" %>
</p>

<% content_for :head do %>
  <script type="text/javascript">
    jQuery(document).ready(function(){

      jQuery('#new_image_link').click(function (event) {
        event.preventDefault();
        jQuery(this).hide();
        jQuery.ajax({type: 'GET', url: this.href, data: ({authenticity_token: AUTH_TOKEN}), success: function(r){ jQuery('#images').html(r);} });
      });

    });
  </script>
<% end %>

app/views/spree/admin/page_images/new.html.erb
<%= render :partial => 'spree/admin/shared/page_tabs', :locals => {:current => "Images"} unless request.xhr? %>

<h3><%= t("new_image") %></h3>

<%= render 'spree/shared/error_messages', :target => @page_image %>

<%= form_for(@page_image, :url => admin_page_images_path(@page), :html => { :multipart => true }) do |form| %>
  <table class="basic-table">
    <%= render "form", :form => form %>
  </table>
  <p class="form-buttons">
    <%= button t("create") %>
    or <%= link_to t("cancel"), "#", :id => "cancel_link" %>
  </p>
<% end %>

<script type="text/javascript">    
  jQuery('#cancel_link').click(function (event) { 
    jQuery('#new_image_link').show();
    jQuery('#images').html('');
  }); 
</script>