config/routes.rb
class Spree::PossiblePage
  def self.matches?(request) 
    return false if request.path =~ /(^\/+(admin|account|cart|checkout|content|login|pg\/|orders|products|s\/|session|signup|shipments|states|t\/|tax_categories|user)+)/
    !Spree::Page.active.find_by_path(request.path).nil?
  end
end

Spree::Core::Engine.routes.append do
  
  namespace :admin do
    
    resources :pages, :constraints => { :id => /.*/ } do
      collection do
        post :update_positions
      end
    
      resources :contents do
        collection do
          post :update_positions
        end
      end
    
      resources :images, :controller => "page_images" do
        collection do
          post :update_positions
        end
      end
    end

  end
  
  constraints(Spree::PossiblePage) do
    get '*page_path', :to => 'pages#show', :as => :page
  end
  
end

app/models/spree/content.rb
class Spree::Content < ActiveRecord::Base

  attr_accessor :delete_attachment
  attr_accessible :page_id, :title, :path, :body, :hide_title, :link, :link_text, :context, :attachment, :delete_attachment

  belongs_to :page
  validates_associated :page
  validates_presence_of :title, :page

  has_attached_file :attachment,
    :styles        => Proc.new{ |clip| clip.instance.attachment_sizes },
    :default_style => :preview,
    :url           => "/spree/contents/:id/:style/:basename.:extension",
    :path          => ":rails_root/public/spree/contents/:id/:style/:basename.:extension"
  
  cattr_reader :per_page
  @@per_page = 10

  scope :for, Proc.new{|context| where(:context => context)}

  before_update :delete_attachment!, :if => :delete_attachment
  before_update :reprocess_images_if_context_changed

  [ :link_text, :link, :body ].each do |property|
    define_method "has_#{property.to_s}?" do
      has_value property
    end
  end

  def has_full_link?
    has_link? && has_link_text?
  end

  def has_image?
    has_value(:attachment_file_name) && attachment_file_name.match(/gif|jpg|png/i)
  end

  def hide_title?
    self.hide_title == true
  end

  def rendered_body
    RDiscount.new(body.to_s).to_html.html_safe
  end

  def default_attachment_sizes
    { :mini => '48x48>', :medium => '427x287>' }
  end

  def attachment_sizes
    case self.context
      when 'slideshow'
        sizes = default_attachment_sizes.merge(:slide => '955x476#')
      else
        sizes = default_attachment_sizes
    end
    sizes
  end

  def context=(value)
    write_attribute :context, value.to_s.parameterize
  end

private

  def delete_attachment!
    del = delete_attachment.to_s
    self.attachment = nil if del == "1" || del == "true"
    true
  end

  def reprocess_images_if_context_changed
    return unless context_changed? && attachment_file_name.present?
    attachment.reprocess!
  end

  def has_value(selector)
    v = self.send selector
    v && !v.to_s.blank?
  end

end

app/controllers/spree/admin/contents_controller.rb
class Spree::Admin::ContentsController < Spree::Admin::ResourceController

  before_filter :load_resource
  before_filter :parent, :only => :index

  before_filter :get_pages, :only => [ :new, :edit, :create, :update ]

  belongs_to 'spree/page'

  def update_positions
    @page = parent
    params[:positions].each do |id, index|
      @page.contents.update_all(['position=?', index], ['id=?', id])
    end
    respond_to do |format|
      format.html { redirect_to admin_page_contents_url(@page) }
      format.js  { render :text => 'Ok' }
    end
  end

  private

    def get_pages
      @pages = Spree::Page.order(:position).all
    end

    def parent
	   @page ||= Spree::Page.find_by_path(params[:page_id])
    end

    def collection
      params[:q] ||= {}
      params[:q][:s] ||= "position asc"
      @search = parent.contents.search(params[:q])
      @collection = @search.result.page(params[:page]).per(Spree::Config[:orders_per_page])
    end

end

app/views/spree/admin/contents/_form.html.erb
<%= form.field_container :title do %>
  <%= form.label :title, t('content.title') %><br />
  <%= form.text_field :title, :class => "title"  %>
  <%= error_message_on :content, :title %>
<% end %>

<%= form.field_container :page do %>
  <%= form.label :page_id, t('content.page') %><br />
  <%= form.select :page_id, @pages.collect{|i| [i.title, i.id]}  %>
  <%= error_message_on :content, :page_id %>
<% end %>

<%= form.field_container :body do %>
  <%= form.label :title, t('content.body') %><%= markdown_helper %><br />
  <%= form.text_area :body  %>
  <%= error_message_on :content, :body %>
<% end %>

<p><%= link_to "Optional Fields <span>&#9650;</span>".html_safe, "#options", :id => "btn_optional" %></p>

<div class="optional" style="display: none;">

  <%= form.field_container :context do %>
    <%= form.label :context, t('content.context') %><br />
    <%= form.text_field :context, :class => "text"  %>
    <%= error_message_on :content, :context %>
  <% end %>

  <%= form.field_container :attachment do %>
    <%= form.label :attachment, t('content.attachment') %><br />
    <%= form.file_field :attachment %>
    <%= error_message_on :content, :attachment %>
  <% end %>
  
  <% if @content.attachment.exists?(:mini) %>
    <%= form.field_container :delete_attachment do %>
      <%= form.check_box :delete_attachment %>
      <%= form.label :delete_attachment, t('content.delete_attachment') %><br />
    <% end %>
  <% end %>
  
  <% if @content.attachment.exists?(:mini) %>
    <p><%= image_tag @content.attachment.url(:mini) %></p>
  <% end %>

  <%= form.field_container :link do %>
    <%= form.label :link, t('content.link') %><br />
    <%= form.text_field :link, :class => "text"  %>
    <%= error_message_on :content, :link %>
  <% end %>
  
  <%= form.field_container :link_text do %>
    <%= form.label :link_text, t('content.link_text') %><br />
    <%= form.text_field :link_text, :class => "text"  %>
    <%= error_message_on :content, :link_text %>
  <% end %>
  
  <%= form.field_container :hide_title do %>
    <%= form.check_box :hide_title, :class => "checkbox"  %>
    <%= form.label :hide_title, t('content.hide_title') %><br />
    <%= error_message_on :content, :hide_title %>
  <% end %>

</div>

<% content_for :head do %>
  <script type="text/javascript">
  //<![CDATA[
    $(document).ready(function() {
      $('#content_body').markItUp(markdownSettings);
      $('#btn_optional').click(function(evt) {
        evt.preventDefault();
        var vis = $('.optional').toggle().css('display') == 'block';
        $(this).find('span').html(vis ? '&#9660;' : '&#9650;');
      });
    }); 
  //]]>
  </script>
<% end %>

app/views/spree/admin/contents/edit.html.erb
<%= render :partial => 'spree/admin/shared/page_tabs', :locals => {:current => 'Contents'} %>

<% if @content.try(:errors).present? %>
  <%= render 'spree/shared/error_messages', :target => @content %>
<% end %>

<h2><%= t('.edit_content') %></h2>

<%= form_for([:admin, @page, @content], :html => { :multipart => true }) do |f| %>
  <%= render "form", :form => f %>
  <p class="form-buttons">
    <%= button t("update") %> <%= t('or') %> <%= link_to t('cancel'), collection_url %>
  </p>
<% end %>

app/views/spree/admin/contents/index.html.erb
<div class='toolbar'>
  <ul class='actions'>
    <li>
      <p><%= button_link_to t('.new_content'), new_object_url, :icon => 'add' %></p>
    </li>
  </ul>
  <br class='clear' />
</div>

<%= render :partial => 'spree/admin/shared/page_tabs', :locals => {:current => 'Contents'} %>

<h2><%= t('.listing_contents') %></h2>

<table class="index sortable" data-sortable-link="<%= update_positions_admin_page_contents_url(@page) -%>">
  <thead>
  <tr>
      <th><%= sort_link @search, :title, t("content.title") %></th>
      <th><%= sort_link @search, :context, t("content.context") %></th>
      <th><%= t("action") %></th>
  </tr>
  </thead>
  <tbody>
    <%- @collection.each do |content|%>
    <tr id="<%= spree_dom_id content %>">
      <td><span class="handle">&nbsp;</span>&nbsp; <%= link_to content.title, object_url(content) %></td>
      <td><%= content.context %>
      <td>
        <%= link_to_edit content %> &nbsp;
        <%= link_to_delete content %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @collection %>

<% content_for :sidebar do %>
  <div class="box">
    <h3><%= t(:search) %></h3>
    <%= search_form_for [:admin, @page, @search] do |f| %>
      <p>
        <%= f.label :title_cont, t('content.title') %><br />
        <%= f.text_field :title_cont, :size => 25 %>
      </p>
      <p>
        <%= f.label :context_cont, t('content.context') %><br />
        <%= f.text_field :context_cont, :size => 25 %>
      </p>
      <p><%= button t("search") %></p>
    <% end %>
  </div>
<% end %>

app/views/spree/admin/contents/new.html.erb
<%= render :partial => 'spree/admin/shared/page_tabs', :locals => {:current => 'Contents'} %>

<% if @content.try(:errors).present? %>
  <%= render 'spree/shared/error_messages', :target => @content %>
<% end %>

<h2><%= t('.new_content') %></h2>

<%= form_for([:admin, @page, @content], :html => { :multipart => true }) do |f| %>
  <%= render "form", :form => f %>

  <p class="form-buttons">
    <%= button t("create") %> <%= t('or') %> <%= link_to t('cancel'), collection_url %>
  </p>
<% end %>

app/views/spree/admin/contents/show.html.erb
<%= render :partial => 'spree/admin/shared/page_tabs', :locals => {:current => 'Contents'} %>

<h2>Content: <%= h @content.title %></h2>

<%= RDiscount.new(@content.body).to_html.html_safe %>

<p>
  <%= link_to_edit @content %>
  <%= link_to t('back'), collection_url %>
</p>